/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerFrame;

import frame.ManageProductFrame;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import model.Cart;
import model.CustomerDataAccess;

/**
 *
 * @author Admin
 */
public class OrderFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrderFrame
     */

    CustomerDataAccess cda=new CustomerDataAccess();
    DefaultTableModel model;
    int rowIndex;
    int cid;
    private double total=0.0;
    public OrderFrame() {
        initComponents();
        tableProduct();        
        jTextField2.setEditable(false);
        cid=cda.getCartID();        
    }
    
    public void tableProduct(){
        JTableHeader header = jTable1.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 15)); // Đặt kích thước chữ 
        header.setPreferredSize(new Dimension(header.getPreferredSize().width, 30)); // Đặt chiều cao là 50px
        jTable1.setDefaultEditor(Object.class, null); // vô hiệu hóa khả năng chỉnh sửa của bảng
        cda.getAllProducts(jTable1);
        model=(DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(120);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLACK);
        jTable1.setBackground(Color.WHITE);
        jTable1.setSelectionBackground(Color.gray);
        jTable1.getTableHeader().setReorderingAllowed(false);
//        TableColumnModel columnModel = jTable1.getColumnModel();
//        for (int i = 0; i < columnModel.getColumnCount(); i++) {
//            columnModel.getColumn(i).setResizable(false); // Cột không thể thay đổi kích thước
//        }
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new OrderFrame.ImageRenderer());
    }
    
    private class ImageRenderer extends DefaultTableCellRenderer{
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel jl=new JLabel();
            if (value != null) {  // Kiểm tra xem value có phải là null không
                byte[] bytes = (byte[]) value;
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(bytes).getImage().getScaledInstance(jTable1.getColumnModel().getColumn(3).getWidth(), 120, Image.SCALE_DEFAULT));
                jl.setIcon(imageIcon);
            } else {
                jl.setText("No Image");  
            }
            return jl;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Price", "Image"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 710, 567));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 33)); // NOI18N
        jLabel2.setText("Total ($): 0.0");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 360, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jalibeicon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 120));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Product Name: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setText("Quantity: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 130, 40));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 270, 50));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 40));

        jButton1.setBackground(new java.awt.Color(223, 24, 54));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 210, 50));

        jButton2.setBackground(new java.awt.Color(223, 24, 54));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 210, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/goback (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 93, 37));

        jButton4.setBackground(new java.awt.Color(223, 24, 54));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 50, 40));

        jButton5.setBackground(new java.awt.Color(223, 24, 54));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 50, 40));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 270, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("Price ($)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new CustomerHomeFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        rowIndex=jTable1.getSelectedRow();
        jTextField2.setText(""+jTable1.getValueAt(rowIndex, 1));
        jTextField4.setText(""+jTable1.getValueAt(rowIndex, 2));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTextField3.getText().isEmpty()){
            jTextField3.setText("1");
        }
        else{
            int count=Integer.parseInt(jTextField3.getText());
            jTextField3.setText(""+(count+1));
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTextField3.getText().isEmpty()){
            jTextField3.setText("0");
        }
        else{
            int count=Integer.parseInt(jTextField3.getText());
            if(count!=0){
                jTextField3.setText(""+(count-1));
            }
            else jTextField3.setText("0");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select a product", "Warning",2);
        } 
        else if(jTextField3.getText().isEmpty() || jTextField3.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "Product quantity is required", "Warning",2);
        }
        else{
            try {
                model = (DefaultTableModel) jTable1.getModel();
                
                int pid=Integer.parseInt(model.getValueAt(rowIndex, 0).toString());
                String pName=jTextField2.getText().trim();
                int qty=Integer.parseInt(jTextField3.getText().trim());
                double price=Double.parseDouble(model.getValueAt(rowIndex, 2).toString());
                double sum=price*qty;
                if(cda.isProductExist(cid, pid)){
                    Cart cart=new Cart();
                    cart.setCid(cid);
                    cart.setPid(pid);
                    cart.setpName(pName);
                    cart.setQty(qty);
                    cart.setPrice(price);
                    cart.setTotal(sum);
                    total+=sum;
                    jLabel2.setText(String.format("Total ($):"+"%.2f",total ));
                    if(cda.insertCart(cart)){
                        JOptionPane.showMessageDialog(this, "Product added!");
                        clear();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Product already in the cart", "Warning",2);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, ""+e, "Warning",2);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(total!=0.0){
            CartFrame cartFrame = new CartFrame(this);
            cartFrame.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "You haven't purchased any product!", "Warning",2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clear(){
        jTextField2.setText(null);
        jTextField3.setText("0");
        jTable1.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
