-- create database food2;
use food2;
-- create table admin(
-- 	id int not null,
--     username varchar(200) default null,
--     password varchar(200) default null,
--     s_ques varchar(200) default null,
--     ans varchar(200) default null,
--     primary key (id)
-- );
-- create table product(
-- 	pid int not null auto_increment,
--     pName varchar (200) default null,
--     price double default null,
--     image mediumblob,
--     primary key(pid)
-- );

-- create table cart(
-- 	cid int default null,
--     pid int default null,
--     pName varchar(45) default null,
--     qty int default null,
--     price double default null,
--     total double default null
-- );

-- create table payment(
-- 	payid int not null auto_increment,
--     cname varchar(200) default null,
--     proid varchar(100) default null,
--     pName varchar(200) default null,
--     total double default null,
--     pDate date default null,	
--     primary key(payid)
-- );
